#!/bin/bash
cf push real-estate-service -m 1G -p target/portal-0.0.1-SNAPSHOT.jar -b https://github.com/dcris/java-buildpack.git --no-route --no-start;
cf bind-service real-estate-service open-discovery-service;
cf bind-service real-estate-service catalog-management-service;
cf bind-service real-estate-service customer-mgt-service;
cf bind-service real-estate-service land-mgt-service;
cf bind-service real-estate-service purchaser-mgt-service;
cf set-env real-estate-service SPRING_PROFILES_ACTIVE cloud;
cf set-env real-estate-service JAVA_OPTS "-XX:+UseG1GC -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:+UseStringDeduplication";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_CLIENTID "portal";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_CLIENTSECRET $3;
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_SCOPE "openid";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_LOGOUT "https://open-uaa."$1"/logout.do";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_CHECKTOKENURL "https://open-uaa."$1"/check_token";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI "https://open-uaa."$1"/oauth/token";
cf set-env real-estate-service SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI "https://open-uaa."$1"/oauth/authorize";
cf set-env real-estate-service SECURITY_OAUTH2_RESOURCE_USERINFOURI "https://open-uaa."$1"/userinfo";
cf set-env real-estate-service SECURITY_OAUTH2_RESOURCE_TOKENINFOURI "https://open-uaa."$1"/check_token";
cf set-env real-estate-service SECURITY_OAUTH2_SUBSCRIBEURI "https://open-uaa."$1"/create_account";
cf set-env real-estate-service SECURITY_OAUTH2_RESOURCE_PREFERTOKENINFO true;
cf set-env real-estate-service SECURITY_OAUTH2_USER_REQUESTURI "https://open-uaa."$1"/Users";
cf set-env real-estate-service SECURITY_OAUTH2_SCIM_ADMIN_SCOPE "scim.read";
cf set-env real-estate-service SECURITY_OAUTH2_GROUP_REQUESTURI "https://open-uaa."$1"/Groups";
cf set-env real-estate-service CATALOG_MGT_SCOPE "catalog_management.user";
cf set-env real-estate-service CUSTOMER_MGT_SCOPE "customer_management.user";
cf set-env real-estate-service LAND_MGT_SCOPE "land_management.user";
cf set-env real-estate-service PURCHASER_MGT_SCOPE "purchaser_management.user";
cf set-env real-estate-service CERT_PATH "cert/"$2"/"$4;
cf set-env real-estate-service CERT_PWD $5;
cf set-env real-estate-service SENDGRID_API_KEY $6;
cf set-env real-estate-service ATTACHMENT_DB_URL $7;
cf set-env real-estate-service ATTACHMENT_DB_USER $8;
cf set-env real-estate-service ATTACHMENT_DB_PWD $9;
cf set-env real-estate-service LOGGING_LEVEL "DEBUG";
cf map-route real-estate-service $1 --hostname portal$4;
cf start real-estate-service;
